{
 "title": "Coherence Members Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor:coherence_cluster_size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor:coherence_cluster_size{cluster=~\"$ClusterName\"}, version)"
   },
   {
    "name": "Services",
    "label": "Services",
    "query": "label_values(vendor:coherence_service_request_max_duration{cluster=~\"$ClusterName\"}, name)"
   },
   {
    "name": "Caches",
    "label": "Caches",
    "query": "label_values(vendor:coherence_cache_size{cluster=~\"$ClusterName\"}, name) "
   },
   { "name": "TopLimit", "label": "Top N Limit", "query": "1,3,10,15" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Members Summary - $ClusterName</h3></center>"
  },
  {
   "title": "Current Cluster Members",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_memory_heap_memory_usage_used{cluster=~\"$ClusterName\"}) by (member, nodeId, site, machine, role)"
    },
    {
     "expr": "sum(vendor:coherence_memory_heap_memory_usage_max{cluster=~\"$ClusterName\"}) by (member, nodeId, site, machine, role)"
    },
    {
     "expr": "sum(vendor:coherence_memory_heap_memory_usage_used{cluster=~\"$ClusterName\"}) by (member, nodeId, site, machine, role) / sum(vendor:coherence_memory_heap_memory_usage_max{cluster=~\"$ClusterName\"}) by (member, nodeId, site, machine, role)  "
    }
   ]
  },
  {
   "title": "Top $TopLimit Total GC Time  - Current Range",
   "type": "table",
   "description": "The top  $TopLimit Members that have the highest Total GC Time over the current time range.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk($TopLimit, sum(delta(vendor:coherence_gc_collection_time{cluster=~\"$ClusterName\"}[$__range])) by (member))"
    }
   ]
  },
  {
   "title": "Top $TopLimit Total GC Count  - Current Range",
   "type": "table",
   "description": "The top  $TopLimit Members that have the highest Total GC Count over the current time range.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk($TopLimit, sum(delta(vendor:coherence_gc_collection_count{cluster=~\"$ClusterName\"}[$__range] )) by (member))"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(vendor:coherence_memory_heap_memory_usage_used{cluster=~\"$ClusterName\"}) / vendor:coherence_memory_heap_memory_usage_max{cluster=~\"$ClusterName\"} * 100",
     "legendFormat": "Member: {{member}} ({{role}})"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_memory_heap_memory_usage_used{cluster=~\"$ClusterName\"}",
     "legendFormat": "Member: {{member}} ({{role}})"
    }
   ]
  },
  {
   "title": "Total Collection Count by Member",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vendor:coherence_gc_collection_count{cluster=~\"$ClusterName\"}[1m])) by(member) > 0",
     "legendFormat": "{{member}}"
    }
   ]
  },
  {
   "title": "Total Garbage Collection Time by Member",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(vendor:coherence_gc_collection_time{cluster=~\"$ClusterName\"}[1m])) by (member) > 0",
     "legendFormat": "{{member}} "
    }
   ]
  },
  {
   "title": "Publisher Success Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_node_publisher_success_rate{cluster=~\"$ClusterName\"}",
     "legendFormat": "Member: {{member}}"
    }
   ]
  },
  {
   "title": "Receiver Success Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vendor:coherence_node_receiver_success_rate{cluster=~\"$ClusterName\"}",
     "legendFormat": "Member: {{member}}"
    }
   ]
  }
 ]
}