{
 "title": "Coherence Persistence Summary Dashboard",
 "tags": [ "dashboard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ClusterName",
    "label": "Cluster Name",
    "query": "label_values(vendor:coherence_cluster_size, cluster)"
   },
   {
    "name": "CoherenceVersion",
    "label": "Coherence Version",
    "query": "label_values(vendor:coherence_cluster_size{cluster=~\"$ClusterName\"}, version)"
   },
   {
    "name": "Services",
    "label": "Services",
    "query": "label_values(vendor:coherence_service_request_max_duration{cluster=~\"$ClusterName\"}, name)"
   },
   {
    "name": "Caches",
    "label": "Caches",
    "query": "label_values(vendor:coherence_cache_size{cluster=~\"$ClusterName\"}, name) "
   },
   { "name": "TopLimit", "label": "Top N Limit", "query": "1,3,5,10,15" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h3>Persistence Summary - $ClusterName</h3></center>"
  },
  {
   "title": "Persistence Enabled Services",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_service_persistence_active_space_used{cluster=~\"$ClusterName\"}) by(name, persistence_mode)"
    },
    {
     "expr": "max(vendor:coherence_service_persistence_latency_max{cluster=~\"$ClusterName\"}) by(name, persistence_mode)"
    }
   ]
  },
  {
   "title": "Active Space Used / Member",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_service_persistence_active_space_used{cluster=~\"$ClusterName\"}) by(member)"
    }
   ]
  },
  {
   "title": "Active Space Used / Machine",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(vendor:coherence_service_persistence_active_space_used{cluster=~\"$ClusterName\"}) by(machine)"
    },
    {
     "expr": "avg(vendor:coherence_service_persistence_active_space_total{cluster=~\"$ClusterName\"}) by(machine)"
    },
    {
     "expr": "avg(vendor:coherence_service_persistence_active_space_available{cluster=~\"$ClusterName\"}) by(machine)"
    },
    {
     "expr": "avg(vendor:coherence_service_persistence_active_space_available{cluster=~\"$ClusterName\"} / vendor:coherence_service_persistence_active_space_total{cluster=~\"$ClusterName\"}) by(machine)"
    }
   ]
  },
  {
   "title": "Active Space Used - All Services",
   "type": "graph",
   "description": "Shows the total active space used by all services.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_service_persistence_active_space_used{cluster=~\"$ClusterName\"})",
     "legendFormat": "Disk Space"
    }
   ]
  },
  {
   "title": "Active Space Used by Service",
   "type": "graph",
   "description": "Shows the total active space used by service.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor:coherence_service_persistence_active_space_used{cluster=~\"$ClusterName\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}