{
 "title": "Sockshop Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": "label_values(application_io_helidon_examples_sockshop_orders_OrderResource_newOrder_seconds, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Instructions",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "\n# Sockshop Dashboard for namespace: $Namespace\n\n\n\nPlease select the namespace above to view details for for that namespace.\n\n\n"
  },
  {
   "title": "Total Orders",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(application_io_helidon_examples_sockshop_orders_OrderResource_newOrder_seconds_count{namespace=~\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Orders Per Second",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(application_io_helidon_examples_sockshop_orders_OrderResource_newOrder_rate_per_second{namespace=~\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Avg Order Processing Time",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(application_io_helidon_examples_sockshop_orders_OrderResource_newOrder_mean_seconds{namespace=~\"$Namespace\"})  "
    }
   ]
  },
  {
   "title": "Successful Payments",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "application_io_helidon_examples_sockshop_payment_DefaultPaymentService_payment_success_total{namespace=~\"$Namespace\"}"
    }
   ]
  },
  {
   "title": "Failed Payments",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "application_io_helidon_examples_sockshop_payment_DefaultPaymentService_payment_failure_total{namespace=~\"$Namespace\"}"
    }
   ]
  },
  {
   "title": "Payment Success Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 4 },
   "targets": [
    {
     "expr": "application_io_helidon_examples_sockshop_payment_DefaultPaymentService_payment_success_total{namespace=~\"$Namespace\"} / (application_io_helidon_examples_sockshop_payment_DefaultPaymentService_payment_success_total{namespace=~\"$Namespace\"} + application_io_helidon_examples_sockshop_payment_DefaultPaymentService_payment_failure_total{namespace=~\"$Namespace\"})"
    }
   ]
  },
  {
   "title": "Orders Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "Orders" }
   ],
   "targets": [
    {
     "expr": "application_io_helidon_examples_sockshop_orders_OrderResource_newOrder_seconds_count{namespace=~\"$Namespace\"} - (application_io_helidon_examples_sockshop_orders_OrderResource_newOrder_seconds_count{namespace=~\"$Namespace\"} offset $__interval)",
     "legendFormat": "Orders"
    }
   ]
  },
  {
   "title": "Payment Processing Over Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_io_helidon_examples_sockshop_payment_DefaultPaymentService_payment_success_total{namespace=~\"$Namespace\"} - (application_io_helidon_examples_sockshop_payment_DefaultPaymentService_payment_success_total{namespace=~\"$Namespace\"} offset $__interval)",
     "legendFormat": "Payment Successes"
    },
    {
     "expr": "application_io_helidon_examples_sockshop_payment_DefaultPaymentService_payment_failure_total{namespace=~\"$Namespace\"} - (application_io_helidon_examples_sockshop_payment_DefaultPaymentService_payment_failure_total{namespace=~\"$Namespace\"} offset $__interval)",
     "legendFormat": "Payment Failures"
    }
   ]
  },
  {
   "title": "Overall Order Processing Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "application_io_helidon_examples_sockshop_orders_OrderResource_newOrder_min_seconds{namespace=~\"$Namespace\"}",
     "legendFormat": "Minimum"
    },
    {
     "expr": "application_io_helidon_examples_sockshop_orders_OrderResource_newOrder_mean_seconds{namespace=~\"$Namespace\"}",
     "legendFormat": "Mean"
    },
    {
     "expr": "application_io_helidon_examples_sockshop_orders_OrderResource_newOrder_max_seconds{namespace=~\"$Namespace\"}",
     "legendFormat": "Maximum"
    }
   ]
  },
  {
   "title": "Average Order Processing Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "application_io_helidon_examples_sockshop_orders_OrderResource_newOrder_mean_seconds{namespace=~\"$Namespace\"}",
     "legendFormat": "Current Average"
    }
   ]
  }
 ]
}